### ISSUE TITLE
Support the experimental FlatList

### ISSUE THREAD

**Issue by brunolemos** [cooperka/react-native-immutable-list-view#10]
There is a new version of the ListView coming.
It's available already under experimental folder. There are some changes on the data format and other methods.

Commit with more details: https://github.com/facebook/react-native/commit/a3457486e39dc752799b1103ebe606224a8e8d32 
Short demo: https://twitter.com/clauderic_d/status/830603226584141824
Long demo: https://www.facebook.com/groups/react.native.community/permalink/921378591331053/

**Comment by cooperka** [comment]
Hey thanks for the link @brunolemos, I'll check it out soon and get back to you here. This could be really cool!

**Comment by brunolemos** [comment]
@cooperka indeed it will!

**Comment by cooperka** [comment]
At first glance it looks as simple as implementing [`getItem: (items: any, index: number) => ?Item`](https://github.com/facebook/react-native/commit/a3457486e39dc752799b1103ebe606224a8e8d32#diff-6e598319db0b64494c59910a5d5b5e24R83) for VirtualizedList! I love this new API. I'll play around with it more this weekend.

I'm not sure yet how it would fit into this library... it could just be a simple wrapper exposed as a secondary export, e.g. `export { ImmutableListView as default, ImmutableFlatList }`. Any thoughts?

**Comment by brunolemos** [comment]
Yeah I think this is the way to go.
`import ImmutableListView, { ImmutableFlatList } from 'react-native-immutable-list-view'`

**Comment by cooperka** [comment]
@brunolemos check it out: https://medium.com/@cooperka/react-native-new-flatlist-component-30db558c7a5b

For now, the new component isn't being exported automatically (you need to explicitly require the file itself). FlatList doesn't support `getItem` so it's impossible to use with Immutable, but the underlying VirtualizedList is what does all the magic.

I'd love your feedback if you have any ideas about how to simplify or make it easier to use!
