### ISSUE TITLE
More social media activity

### ISSUE THREAD

**Issue by cooperka** [cooperka/react-native-immutable-list-view#11]
This repo seems to have only moderate usage, but also a higher stars/user ratio than average, which tells me that the people using it find it helpful, but it's only being discovered by people who already know exactly what they need.

I wrote an article about it [on Medium](https://medium.com/@cooperka/react-native-immutable-listview-6075b7e27665), which also has high engagement but a low number of total views. SEO is pretty low when searching for either one; the article doesn't even show up in Google results when searching for the exact title.

If anyone has ideas for how to improve visibility, I'm all ears! :cat:

**Comment by booboothefool** [comment]
Does this solve the issue of ListView leaking memory? https://github.com/facebook/react-native/issues/499

That's how I arrived here.

**Comment by cooperka** [comment]
@booboothefool haha what do you mean? This issue is definitely not related.

**Comment by booboothefool** [comment]
@cooperka Apologies. Was referring to the issue https://github.com/facebook/react-native/issues/12512 where scrolling down very long lists continues to leak memory and slow the app to a crawl. FlatList was supposed to help, but it doesn't for me, as well as the other guy in the issue. I found out about FlatList from your article on Medium. 👍

**Comment by cooperka** [comment]
Gotcha! Yeah brentvatne's comments on https://github.com/facebook/react-native/issues/12512 are very accurate. I would try profiling your app and trying to figure out exactly what is causing the slowness. It's probably not the ListView itself (especially if FlatList didn't fix the issue), but more likely other code that's being executed as you scroll.

If you could create a demo app that we can install and run on our own machines, that would really help us diagnose your problem.
