### ISSUE TITLE
Make consistent FlatList require

### ISSUE THREAD

**Issue by grundmanise** [cooperka/react-native-immutable-list-view#13]
First of all, thanks for such a great component!

I found your lib through your medium blog post, and installed `FlatList` using[ provided bash](https://gist.github.com/cooperka/c5dd3ab11f588044d4d6ba22d52c4ab0#file-getflatlist-bash) which installs to the `.../CustomComponents/Lists`, but this component requires it from `node_modules/react-native/Libraries/Experimental/`, maybe we should change the `FlatList` `import` path to the `CustomComponents/Lists` as the install path from blog?

**Comment by cooperka** [comment]
Absolutely! Feel free to submit a PR. Otherwise, I should have time to get around to this later today now that it's the weekend.

**Comment by cooperka** [comment]
@grundmanise it should be fixed as of v0.3.1 now :)
