### ISSUE TITLE
Missing ScrollTo

### ISSUE THREAD

**Issue by loiclouvet** [cooperka/react-native-immutable-list-view#14]
Hello,

It would be nice to implement and map ScrollTo method 
e.g. https://facebook.github.io/react-native/docs/listview.html#scrollto

**Comment by cooperka** [comment]
Hi @loiclouvet, great suggestion -- I'll try to add this within the next few weeks. Feel free to submit a PR in the meantime 🍺

**Comment by cooperka** [comment]
This is added as of v0.4.2 :smiley_cat:
