### ISSUE TITLE
npm install react-native-immutable-list-view --save warning

### ISSUE THREAD

**Issue by lucasleelz** [cooperka/react-native-immutable-list-view#21]
```
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.6
└─┬ react-native-immutable-list-view@0.4.3 
  └── immutable@3.8.1 

```

npm WARN react-native-immutable-list-view@0.4.3 requires a peer of react@>=15.1

**Comment by cooperka** [comment]
Unfortunately, semver doesn't match alpha releases (or anything that comes after the dash) when using version ranges. Even using `*` would not work, so this warning seems to be impossible to get rid of.

You can try the calculator here to see how it behaves: https://semver.npmjs.com/

**Comment by lucasleelz** [comment]
Thank you for your answer

**Comment by cooperka** [comment]
This should actually be fixed by https://github.com/cooperka/react-native-immutable-list-view/commit/cd1f228acb89b366e1dcc626efd34f8a9f353713 now :)
