### ISSUE TITLE
Publish new version that uses stable VirtualizedList

### ISSUE THREAD

**Issue by cooperka** [cooperka/react-native-immutable-list-view#22]
The stable version of `VirtualizedList` is available in the published version of React Native as of v0.43 (under `Libraries/CustomComponents/Lists`). I plan to make a major version update to support this and then ANOTHER major version update to support v0.44 after the component moves directories again (under `Libraries/Lists`).

The final update to use `Libraries/Lists` is planned to be version 1.0.0 of this module :)

**Comment by andon** [comment]
I think you can close this now :) 
With 0.5.0 release, you already use **real** VirtualizedList that is under Libraries/Lists in RN 0.44:
https://github.com/cooperka/react-native-immutable-list-view/blob/5ec537c7215893b86a501a67359abb583d6b6001/src/ImmutableVirtualizedList.js#L3

**Comment by cooperka** [comment]
Yes indeed! It worked out better than originally expected. I'm still going to release 1.0.0 soon, hopefully this weekend if I make the time for it.
