### ISSUE TITLE
Sorted Immutable Map Not Rendering Correctly

### ISSUE THREAD

**Issue by mmoravec** [cooperka/react-native-immutable-list-view#23]
I have an immutable map that looks like:

data = {
---header1: {
------prop1:
------prop2:
------etc...
---}
---header2: {
------etc...
---}
}

I can't figure out how to get the headers to show up in the correct order with this library. i.e. 

header1
   header1 data 
header2
   header2 data

They are currently displaying

header2
   data
header1
  data

Do I need to set a section ID somewhere?

**Comment by cooperka** [comment]
Hi @mmoravec, it's possible there's a bug, but I don't think JavaScript makes any guarantees about ordering for objects. You could try using this to preserve order:

```js
Immutable.OrderedMap([[key1, value1], [key2, value2]])
```

If that doesn't work, please post a working demo app and I can take a look!

P.S. to format code on GitHub and preserve indentation, you can surround your code with triple ticks on the lines above and below (```).

**Comment by mmoravec** [comment]
Hey @cooperka thanks for the tips, I'll let you know how the OrderedMap works out.

**Comment by mmoravec** [comment]
OrderedMap works well. Thanks!
