### ISSUE TITLE
Iterable.length warnings with ImmutableVirtualizedList

### ISSUE THREAD

**Issue by loiclouvet** [cooperka/react-native-immutable-list-view#26]
Hello there !

I'm getting following warnings when using ImmutableVirtualizedList

```
YellowBox.js:71 iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at Object.getItemCount (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:96434:37)
    at VirtualizedList.render (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:40071:34)
```

It seems to be linked to this line:
`getItemCount={(items) => (items.size || items.length || 0)}`

Should we remove `items.length` removed as warning says ?

**Stack:**
immutable: ^3.8.1
react-native-immutable-list-view: ^0.5.0

**Comment by cooperka** [comment]
Hi @loiclouvet, this is caused when `items.size` is 0 so it mistakenly falls back to trying to get `items.length`. Silly oversight on my part, it was just meant as a backup to allow Immutable data containing mutable data.

In the next release, I'm going to disallow this type of mixed data and this will no longer be an issue; I'll remove `items.length`. Thanks for the report!

**Comment by loiclouvet** [comment]
@cooperka Thanks ! Will upgrade react-native-immutable-list-view as soon as you publish 0.5.1 on npm ! ;)

**Comment by cooperka** [comment]
Ah, too busy updating the tag I forgot to publish there. It's published now 🍻
