### ISSUE TITLE
Question: Any plans to wrap SectionList? 

### ISSUE THREAD

**Issue by anderswag** [cooperka/react-native-immutable-list-view#32]
Just wondering if this is something enough people would want

**Comment by cooperka** [comment]
Definitely -- I'd love to do this eventually, and I'd be happy to review a PR for it if you're willing to help!

**Comment by Leeds-eBooks** [comment]
Supporting Map might be an easier first PR https://github.com/cooperka/react-native-immutable-list-view/issues/25

**Comment by cooperka** [comment]
@Leeds-eBooks I think we get Map for free after supporting SectionList! This is a dupe issue.

The refactoring I mentioned earlier was completed so it should be very easy to add support; I'm currently working on other things, but I'm happy to review any PRs.
