### ISSUE TITLE
Warning: setState(...): Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by brunolemos** [cooperka/react-native-immutable-list-view#6]
> This usually means you called setState() on an unmounted component.
> Please check the code for the ImmutableListView component.

I have a listview of listviews, something similar to Trello columns.
This happens when I add a new column to the mix.

[![devhub.png](https://s24.postimg.org/ur6gdnyr9/Screen_Shot_2016_12_13_at_16_46_27.png)](https://postimg.org/image/v3xujuh0x/)

**Comment by cooperka** [comment]
Thanks for the report, @brunolemos. Could you please give some more context for exactly where and what is causing this? A demo project or example code would be really helpful.

In the meantime, this warning can safely be ignored. It just means a component that doesn't exist anymore is trying to update itself. There's probably a subscription that wasn't cleaned up somewhere. In some cases that can lead to memory leaks if this happens a lot.

**Comment by brunolemos** [comment]
@cooperka I don't have a small reproducible code right now, but apparently it only happens if I use the `rowsDuringInteraction` property.

**Comment by cooperka** [comment]
I also use that prop, and I don't get this issue... not sure what could be going on. If you have some time to get a mock app together to reproduce this that would be really helpful!

**Comment by cooperka** [comment]
The issue makes sense now -- since `setState` is being called asynchronously in `runAfterInteractions`, it's very likely that the component could be unmounted in the interim (especially with multiple of them at once). It's been resolved now as of [`v0.2.2`](https://github.com/cooperka/react-native-immutable-list-view/releases).
